[build]
target-dir = "target"

[target.bpfel-unknown-none]
linker = "bpf-linker"

[target.x86_64-unknown-linux-gnu]
linker = "clang"
rustflags = ["-C", "link-arg=-fuse-ld=lld"]

[alias]
xtask = "run --package xtask --"